/**
 * Brain OpenCode Plugin
 *
 * Registers Brain knowledge graph tools and lifecycle hooks for OpenCode.
 * Generated by `brain init --opencode`. Tool registrations call the Brain
 * HTTP API; lifecycle hooks track session start/end automatically.
 *
 * This file is a reference implementation. When `brain init --opencode` runs,
 * it generates a copy with the correct API base URL and auth token embedded.
 */
import type { Plugin } from "@opencode-ai/plugin";

// These values are replaced by `brain init --opencode` at generation time.
// For local development, override via environment variables.
const API_BASE = process.env.BRAIN_API_BASE ?? "http://localhost:3000/api/mcp/WORKSPACE_ID";
const AUTH_TOKEN = process.env.BRAIN_AUTH_TOKEN ?? "";

async function brainFetch(path: string, body: Record<string, unknown>): Promise<unknown> {
  const res = await fetch(`${API_BASE}${path}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${AUTH_TOKEN}`,
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`Brain API error: ${res.status} ${await res.text()}`);
  return res.json();
}

export default {
  name: "brain",

  tools: {
    "task-context": {
      description: "Get task details and context from the Brain knowledge graph",
      parameters: { task_id: { type: "string", description: "The task identifier" } },
      async execute({ task_id }) {
        return brainFetch("/task-context", { task_id });
      },
    },
    "project-context": {
      description: "Get project overview and decisions from the Brain knowledge graph",
      parameters: { project_id: { type: "string", description: "The project identifier" } },
      async execute({ project_id }) {
        return brainFetch("/project-context", { project_id });
      },
    },
    "status-update": {
      description: "Update task status in the Brain knowledge graph",
      parameters: {
        task_id: { type: "string", description: "The task identifier" },
        status: { type: "string", description: "New status: open|todo|ready|in_progress|blocked|done|completed" },
        reason: { type: "string", description: "Reason for status change (required for blocked)", optional: true },
      },
      async execute({ task_id, status, reason }) {
        return brainFetch("/tasks/status", { task_id, status, reason });
      },
    },
    observations: {
      description: "Log an observation (risk, conflict, or signal) to the Brain knowledge graph",
      parameters: {
        text: { type: "string", description: "What was observed" },
        severity: { type: "string", description: "Severity: info|warning|conflict" },
        category: { type: "string", description: "Category: architecture|security|performance|data|ux|other" },
      },
      async execute({ text, severity, category }) {
        return brainFetch("/observations", { text, severity, category });
      },
    },
  },

  hooks: {
    "session.created": async ({ session }) => {
      await brainFetch("/sessions/start", { agent: "opencode" });
    },
    "session.idle": async ({ session }) => {
      await brainFetch("/sessions/end", {
        session_id: session?.id,
        summary: "Session ended",
      });
    },
  },
} satisfies Plugin;
