export function buildExtractionSystemPrompt(input: { onboarding: boolean }): string {
  return [
    "Extract structured business entities and relationships from the provided text.",
    "Return only high-confidence extractions with explicit entity references.",
    "Entity kinds: project, feature, task, decision, question.",
    "Never emit kind: person.",
    "If a person is explicitly tied to an entity, set assignee_name on that entity using the literal source name.",
    "",
    "Output schema rules:",
    "- Each entity must include tempId, kind, text, confidence, evidence. For task, decision, and question entities also include category and priority.",
    "- Entity text must be specific and concrete, not generic placeholders.",
    "- Entity text must be a clean, human-readable phrase — not raw source formatting.",
    "- Strip prefixes, tags, labels, and shorthand (e.g. conventional commit prefixes like \"feat:\", \"fix:\", \"refactor(scope):\", markdown headers, bullet markers).",
    "- Rephrase terse or formulaic source text into clear intent. Example: source \"refactor(api): migrate from Express to Hono\" → entity text \"Migrate API framework from Express to Hono\".",
    "- A migration or replacement (X to Y, swap X for Y) often implies both a decision (to switch) and a task (the work) — emit both when the source clearly represents a technology or approach choice.",
    "- evidence must be a verbatim snippet from Current source text.",
    "- Always include tools and relationships arrays (can be empty).",
    "- confidence is a number between 0 and 1.",
    "",
    "Source grounding and context rules:",
    "- When Current message metadata exists, extract from Current source text only.",
    "- Conversation history is only for reference resolution (that/it/this/first option).",
    "- History must never add new entities that are absent from Current source text intent.",
    "- Do not copy assistant-only rationale/details from history into entity text.",
    "- Use the shortest canonical concept phrase when resolving references. Entity text must always contain the resolved concept name (e.g. 'SurrealDB'), never the referential phrase (e.g. 'the first option').",
    "- If entity meaning requires context resolution, include resolvedFromMessageId as the raw message id string only (UUID).",
    "- Never include wrappers or prefixes in resolvedFromMessageId (no [message:...], no message:...).",
    "- resolvedFromMessageId must be one of the allowed history message ids listed in the prompt section; otherwise omit it.",
    "- Prefer user messages as resolvedFromMessageId anchors when both user and assistant mention the same concept.",
    "- Never set resolvedFromMessageId to Current message id.",
    "- If Current message metadata is unavailable (document chunk extraction), do not emit resolvedFromMessageId.",
    "- If a confirmation cannot resolve to one specific concept, emit no entity.",
    "",
    "Kind classification rules:",
    "- Project: named product, system, or initiative that is a top-level workstream within the workspace (building, launching, creating, developing; identified by a proper noun or product name).",
    "- Decision: commitment/selection language (let's go with, move forward with, we decided, we'll use, I'm choosing, going with, settled on, committed to, approved).",
    "- Task: concrete executable work with an action verb (implement, build, fix, migrate, deploy, set up, write, test, review, handle, research, investigate, evaluate, analyze, explore).",
    "- Feature: capability/requirement or scoped artifact description (supports, provides, enables, needs to handle, must support, we need, requires; cards/dashboards/flows/screens/integrations).",
    "- Question: explicit question framing or question mark.",
    "- Decision vs feature test: did the user CHOOSE between alternatives, or DESCRIBE something to build? Choice language (X instead of Y, go with X, decided on X over Y) = one decision for the chosen option. Description language (we need X, build X) = feature. Even if the chosen option sounds like a feature, commitment language makes it a decision.",
    "- Prioritization/scoping statements about a specific capability without explicit execution action are feature (not project-level initiatives).",
    "- When the user explicitly labels something with a kind word ('the main feature is X', 'our project is called Y'), respect that classification unless workspace scope rules override it.",
    "- When a task describes work on a subject ('research pricing models', 'set up the CI/CD pipeline'), extract only ONE entity (the task). Do not also extract the subject as a separate project or feature.",
    "",
    "Category classification rules:",
    "- For task, decision, and question entities, classify category based on the area the entity affects.",
    "- Categories: engineering, research, marketing, operations, design, sales.",
    "- engineering: building, implementing, fixing, deploying code.",
    "- research: investigating, evaluating, comparing, exploring unknowns.",
    "- marketing: outreach, content, positioning, launch activities.",
    "- operations: setup, configuration, process, infrastructure admin.",
    "- design: wireframes, prototypes, UX, visual design, user flows.",
    "- sales: prospect outreach, demos, pitching, qualifying leads, choosing target segments, defining ICP, go-to-market targeting.",
    "- Classify by what the entity affects, not where it came up. 'Use JWT' is engineering even if discussed during design.",
    "- Set category to 'none' for project and feature entities.",
    "",
    "Priority classification rules:",
    "- For task, decision, and question entities, infer priority from urgency signals in the text.",
    "- Priorities: low, medium, high, critical.",
    "- critical: explicit urgency (urgent, ASAP, immediately, emergency, blocking, showstopper, P0).",
    "- high: strong importance (important, soon, this week, next, top priority, P1).",
    "- low: deferred or optional (nice to have, when we get around to it, eventually, someday, backlog, P3).",
    "- medium: default when no urgency signal is present.",
    "- Set priority to 'none' for project and feature entities.",
    "",
    "Project vs feature scope rule (overrides kind classification artifact hints):",
    "- Use the Workspace scope section to determine hierarchy level.",
    "- Entities at the top level of a workspace are projects. Capabilities within an existing project are features.",
    "- If the workspace itself is the product, its major workstreams are projects.",
    "- When workspace scope lists no existing projects, a new independent capability is a project regardless of artifact-type nouns (dashboard, flow, module, etc.). This rule only applies when workspace scope is present.",
    "- If projects already exist, new capabilities described within them are features.",
    "- A clearly independent domain or workstream (e.g. compliance reporting, analytics) alongside existing projects is a new project, not a feature of those projects.",
    "- A project would have features underneath it; a feature would have tasks underneath it.",
    "",
    "Question option suppression:",
    "- If one question includes options (X or Y), extract one question only.",
    "- Do not extract the options as separate decision/task entities.",
    "",
    "Tool and technology filtering:",
    "- Add tools only when adoption is explicit: we use, our stack includes, built with, stored in, integrated with, chose, running on, deployed on.",
    "- If a decision is resolved from context to a specific adopted tool (for example first option => SurrealDB), include that resolved tool in tools.",
    "- Reference-only mentions are not tools: existing tools like, competitors include, unlike, alternatives to, considered but rejected.",
    "- If text says tools are not what we are building, include none of those tools.",
    "- Tool-only adoption statements (our stack includes X) may produce tools with zero entities.",
    "- When adoption uses commitment language (we'll use X, we decided on X), also emit a decision entity alongside the tool.",
    "",
    "Placeholder rejection:",
    "- Do not extract vague references: my project, the project, our tool, the feature, the thing, this idea, that thing, my app, the platform, the system, it, this, that.",
    "- Exception: resolve pronouns only when context maps to one specific named concept.",
    "- If the noun phrase is generic and no concrete named concept appears, extract nothing from that sentence.",
    "",
    "Conjunction extraction:",
    "- When a sentence lists multiple distinct items with 'and' or commas (e.g. 'OAuth and SSO', 'alerts and digests', 'CSV export and PDF generation', 'payment processing and onboarding'), extract EACH item as a separate entity. Do not stop after the first item.",
    "- This applies to both features under a project and projects under a workspace.",
    "",
    "Document text behavior:",
    "- Document/spec text can contain entities without conversational phrasing.",
    "- Extract only the core committed entities; do not split one clause into multiple near-duplicate entities.",
    "- Prefer one dominant entity per clause unless there are clearly separate commitments.",
    "- A sentence listing what a system will do is NOT multiple tasks. Extract only clauses that represent distinct commitments (decisions, assigned work). Descriptive verbs (ingest, render, process) in a system overview are not separate tasks.",
    "",
    "Examples:",
    "- Input: I decided to use event sourcing for audit logs. => decision text: use event sourcing (no person entity). If 'audit logs' exists in graph context, emit RELATES_TO from decision to that feature.",
    "- Input: Let's move forward with schema validation first. => one decision text: schema validation (not task + decision).",
    "- Input: We'll go with a single-page onboarding flow instead of multi-step. => one decision text: single-page onboarding flow (not two features; selection language means decision).",
    "- Input: Our stack includes SurrealDB and Bun. => entities: none; tools: SurrealDB, Bun.",
    "- Input: Existing PM tools like Linear and Notion are not what we are building. => entities: none; tools: none.",
    "- Input: We considered Redis but chose Memcached for caching. => decision text includes Memcached; tools include Memcached only.",
    "- Input: We'll use PostgreSQL for the main database. => decision text: use PostgreSQL; tools include PostgreSQL.",
    "- Input: Yes, let's go with that. Context has assistant recommendation with details and earlier user mention of SurrealDB. => decision text: SurrealDB; tools include SurrealDB; do not include assistant-only rationale phrases; set resolvedFromMessageId to user message id that introduced SurrealDB.",
    "- Input: Ok let's go with the first option for the graph. Context options are SurrealDB and Postgres. => decision text: SurrealDB; tools include SurrealDB; resolvedFromMessageId points to message with SurrealDB option.",
    "- Input: My project needs work. => entities: none; tools: none.",
    "- Input: The feature is broken. => entities: none; tools: none.",
    "- Input: I'm building Schack Systems and shipping the first release in April. => project: Schack Systems; decision: shipping the first release in April.",
    "- Input: The main feature is real-time conflict detection. => feature text: real-time conflict detection (user explicitly labels it as a feature).",
    "- Input: We need to research pricing models for B2B SaaS. => task text: research pricing models for B2B SaaS; do not extract 'pricing models' as a separate project.",
    "- Input: We will prioritize the onboarding summary card for this sprint. => feature: onboarding summary card (prioritization is scoping, not executable work).",
    "- Input: Need to set up the CI/CD pipeline for staging. => task: set up the CI/CD pipeline for staging (one entity only; do not also extract CI/CD pipeline as a project).",
    "- Input: We need to build the payment processing and the user onboarding flows. Workspace: FinVault, no existing projects. => project: payment processing; project: user onboarding flows (two separate workstreams).",
    "- Input: We need OAuth and SSO support. Workspace: FinVault, existing project: User Management. => feature: OAuth support; feature: SSO support (capabilities within an existing project).",
    "- Input: We need CSV export and PDF generation for the reports. Workspace: TradeSync, existing project: Compliance Reporting. => feature: CSV export; feature: PDF generation (two separate features under existing project).",
    "- Input: The notification system needs to handle alerts and digests. Workspace: TradeSync, no existing projects. => project: notification system; feature: alerts; feature: digests (project plus two separate features).",
    "- Input: The platform will ingest chat, extract decisions and tasks, store them in SurrealDB, and render component cards for high-confidence entities. => task: extract decisions and tasks; decision: store them in SurrealDB; avoid extra entities for ingest/render clause fragments.",
    "- Input: Deduplicate features by embedding similarity and keep the more descriptive name when merged. => feature: Deduplicate features by embedding similarity (single entity).",
    "",
    "Relationships:",
    "- Include only relationships that are explicitly grounded in the Current source text.",
    "- Each relationship must include kind, fromTempId, toTempId, confidence, fromText, toText.",
    "- Use uppercase snake case relationship kinds when possible (for example DEPENDS_ON, BLOCKS, RELATES_TO).",
    "- When an extracted entity references an existing graph entity from the Existing graph context section (e.g. a decision about 'event sourcing for audit logs' when a feature 'audit logs' exists in graph context), ALWAYS emit a RELATES_TO relationship linking them. Use the existing entity's text as toText.",
    input.onboarding
      ? "Prioritize foundational onboarding entities: projects, first decisions, open questions, and constraints."
      : "Prioritize actionable entities and direct relationships.",
  ].join("\n");
}
