export function buildExtractionSystemPrompt(input: { onboarding: boolean }): string {
  return [
    "Extract structured business entities and relationships from the provided text.",
    "Return only high-confidence extractions with explicit entity references.",
    "Entity kinds: project, feature, task, decision, question.",
    "Never emit kind: person.",
    "If a person is explicitly tied to an entity, set assignee_name on that entity using the literal source name.",
    "",
    "Output schema rules:",
    "- Each entity must include tempId, kind, text, confidence, evidence.",
    "- Entity text must be specific and concrete, not generic placeholders.",
    "- evidence must be a verbatim snippet from Current source text.",
    "- Always include tools and relationships arrays (can be empty).",
    "- confidence is a number between 0 and 1.",
    "",
    "Source grounding and context rules:",
    "- When Current message metadata exists, extract from Current source text only.",
    "- Conversation history is only for reference resolution (that/it/this/first option).",
    "- History must never add new entities that are absent from Current source text intent.",
    "- Do not copy assistant-only rationale/details from history into entity text.",
    "- Use the shortest canonical concept phrase when resolving references.",
    "- If entity meaning requires context resolution, include resolvedFromMessageId with the exact [message:<id>] where concept originates.",
    "- Prefer user messages as resolvedFromMessageId anchors when both user and assistant mention the same concept.",
    "- Never set resolvedFromMessageId to Current message id.",
    "- If Current message metadata is unavailable (document chunk extraction), do not emit resolvedFromMessageId.",
    "- If a confirmation cannot resolve to one specific concept, emit no entity.",
    "",
    "Kind classification rules:",
    "- Decision: commitment/selection language (let's go with, move forward with, we decided, I'm choosing, going with, settled on, committed to, approved).",
    "- Task: concrete executable work with an action verb (implement, build, fix, migrate, deploy, set up, write, test, review, handle).",
    "- Feature: capability/requirement or scoped artifact description (supports, provides, enables, needs to handle, must support; cards/dashboards/flows/screens/integrations).",
    "- Question: explicit question framing or question mark.",
    "- Option selection between alternatives is decision, not task.",
    "- Prioritization/scoping statements without explicit execution action are feature.",
    "",
    "Question option suppression:",
    "- If one question includes options (X or Y), extract one question only.",
    "- Do not extract the options as separate decision/task entities.",
    "",
    "Tool and technology filtering:",
    "- Add tools only when adoption is explicit: we use, our stack includes, built with, stored in, integrated with, chose, running on, deployed on.",
    "- Reference-only mentions are not tools: existing tools like, competitors include, unlike, alternatives to, considered but rejected.",
    "- Tool-only adoption statements may produce tools with zero entities.",
    "",
    "Placeholder rejection:",
    "- Do not extract vague references: my project, the project, our tool, the feature, the thing, this idea, that thing, my app, it, this, that.",
    "- Exception: resolve pronouns only when context maps to one specific named concept.",
    "",
    "Document text behavior:",
    "- Document/spec text can contain entities without conversational phrasing.",
    "- Extract only the core committed entities; do not split one clause into multiple near-duplicate entities.",
    "- Prefer one dominant entity per clause unless there are clearly separate commitments.",
    "",
    "Examples:",
    "- Input: I decided to use event sourcing for audit logs. => decision text: use event sourcing (no person entity).",
    "- Input: Let's move forward with schema validation first. => one decision text: schema validation (not task + decision).",
    "- Input: Our stack includes SurrealDB and Bun. => entities: none; tools: SurrealDB, Bun.",
    "- Input: We considered Redis but chose Memcached for caching. => decision text includes Memcached; tools include Memcached only.",
    "- Input: Yes, let's go with that. Context has assistant recommendation with details and earlier user mention of SurrealDB. => decision text: SurrealDB; do not include assistant-only rationale phrases; set resolvedFromMessageId to user message id that introduced SurrealDB.",
    "- Input: Ok let's go with the first option for the graph. Context options are SurrealDB and Postgres. => decision text: SurrealDB; resolvedFromMessageId points to message with SurrealDB option.",
    "- Input: The platform will ingest chat, extract decisions and tasks, store them in SurrealDB, and render component cards for high-confidence entities. => task: extract decisions and tasks; decision: store them in SurrealDB; do not emit extra duplicate feature/task fragments.",
    "- Input: Deduplicate features by embedding similarity and keep the more descriptive name when merged. => feature: Deduplicate features by embedding similarity (single entity).",
    "",
    "Relationships:",
    "- Include only relationships that are explicitly grounded in the Current source text.",
    "- Each relationship must include kind, fromTempId, toTempId, confidence, fromText, toText.",
    "- Use uppercase snake case relationship kinds when possible (for example DEPENDS_ON, BLOCKS, RELATES_TO).",
    input.onboarding
      ? "Prioritize foundational onboarding entities: projects, first decisions, open questions, and constraints."
      : "Prioritize actionable entities and direct relationships.",
  ].join("\n");
}
