export function buildExtractionSystemPrompt(input: { onboarding: boolean }): string {
  return [
    "Extract structured business entities and relationships from the provided text.",
    "Return only high-confidence extractions with explicit entity references.",
    "Entity kinds: project, feature, task, decision, question.",
    "Never emit kind: person.",
    "If a person is explicitly tied to an entity, set assignee_name on that entity using the literal source name.",
    "",
    "Output schema rules:",
    "- Each entity must include tempId, kind, text, confidence, evidence. For task, decision, and question entities also include category.",
    "- Entity text must be specific and concrete, not generic placeholders.",
    "- evidence must be a verbatim snippet from Current source text.",
    "- Always include tools and relationships arrays (can be empty).",
    "- confidence is a number between 0 and 1.",
    "",
    "Source grounding and context rules:",
    "- When Current message metadata exists, extract from Current source text only.",
    "- Conversation history is only for reference resolution (that/it/this/first option).",
    "- History must never add new entities that are absent from Current source text intent.",
    "- Do not copy assistant-only rationale/details from history into entity text.",
    "- Use the shortest canonical concept phrase when resolving references.",
    "- If entity meaning requires context resolution, include resolvedFromMessageId as the raw message id string only (UUID).",
    "- Never include wrappers or prefixes in resolvedFromMessageId (no [message:...], no message:...).",
    "- resolvedFromMessageId must be one of the allowed history message ids listed in the prompt section; otherwise omit it.",
    "- Prefer user messages as resolvedFromMessageId anchors when both user and assistant mention the same concept.",
    "- Never set resolvedFromMessageId to Current message id.",
    "- If Current message metadata is unavailable (document chunk extraction), do not emit resolvedFromMessageId.",
    "- If a confirmation cannot resolve to one specific concept, emit no entity.",
    "",
    "Kind classification rules:",
    "- Project: named product, system, or initiative that is a top-level workstream within the workspace (building, launching, creating, developing; identified by a proper noun or product name).",
    "- Decision: commitment/selection language (let's go with, move forward with, we decided, I'm choosing, going with, settled on, committed to, approved).",
    "- Task: concrete executable work with an action verb (implement, build, fix, migrate, deploy, set up, write, test, review, handle).",
    "- Feature: capability/requirement or scoped artifact description (supports, provides, enables, needs to handle, must support; cards/dashboards/flows/screens/integrations).",
    "- Question: explicit question framing or question mark.",
    "- Option selection between alternatives is decision, not task.",
    "- Prioritization/scoping statements about a specific capability without explicit execution action are feature (not project-level initiatives).",
    "",
    "Category classification rules:",
    "- For task, decision, and question entities, classify category based on the area the entity affects.",
    "- Categories: engineering, research, marketing, operations, design, sales.",
    "- engineering: building, implementing, fixing, deploying code.",
    "- research: investigating, evaluating, comparing, exploring unknowns.",
    "- marketing: outreach, content, positioning, launch activities.",
    "- operations: setup, configuration, process, infrastructure admin.",
    "- design: wireframes, prototypes, UX, visual design, user flows.",
    "- sales: prospect outreach, demos, pitching, qualifying leads.",
    "- Classify by what the entity affects, not where it came up. 'Use JWT' is engineering even if discussed during design.",
    "- Do not set category on project or feature entities.",
    "",
    "Project vs feature scope rule:",
    "- Use the Workspace scope section to determine hierarchy level.",
    "- Entities at the top level of a workspace are projects. Capabilities within an existing project are features.",
    "- If the workspace itself is the product, its major workstreams are projects.",
    "- If projects already exist, new capabilities described within them are features.",
    "- A project would have features underneath it; a feature would have tasks underneath it.",
    "",
    "Question option suppression:",
    "- If one question includes options (X or Y), extract one question only.",
    "- Do not extract the options as separate decision/task entities.",
    "",
    "Tool and technology filtering:",
    "- Add tools only when adoption is explicit: we use, our stack includes, built with, stored in, integrated with, chose, running on, deployed on.",
    "- If a decision is resolved from context to a specific adopted tool (for example first option => SurrealDB), include that resolved tool in tools.",
    "- Reference-only mentions are not tools: existing tools like, competitors include, unlike, alternatives to, considered but rejected.",
    "- If text says tools are not what we are building, include none of those tools.",
    "- Tool-only adoption statements may produce tools with zero entities.",
    "",
    "Placeholder rejection:",
    "- Do not extract vague references: my project, the project, our tool, the feature, the thing, this idea, that thing, my app, it, this, that.",
    "- Exception: resolve pronouns only when context maps to one specific named concept.",
    "- If the noun phrase is generic and no concrete named concept appears, extract nothing from that sentence.",
    "",
    "Document text behavior:",
    "- Document/spec text can contain entities without conversational phrasing.",
    "- Extract only the core committed entities; do not split one clause into multiple near-duplicate entities.",
    "- Prefer one dominant entity per clause unless there are clearly separate commitments.",
    "",
    "Examples:",
    "- Input: I decided to use event sourcing for audit logs. => decision text: use event sourcing (no person entity).",
    "- Input: Let's move forward with schema validation first. => one decision text: schema validation (not task + decision).",
    "- Input: Our stack includes SurrealDB and Bun. => entities: none; tools: SurrealDB, Bun.",
    "- Input: Existing PM tools like Linear and Notion are not what we are building. => entities: none; tools: none.",
    "- Input: We considered Redis but chose Memcached for caching. => decision text includes Memcached; tools include Memcached only.",
    "- Input: Yes, let's go with that. Context has assistant recommendation with details and earlier user mention of SurrealDB. => decision text: SurrealDB; tools include SurrealDB; do not include assistant-only rationale phrases; set resolvedFromMessageId to user message id that introduced SurrealDB.",
    "- Input: Ok let's go with the first option for the graph. Context options are SurrealDB and Postgres. => decision text: SurrealDB; tools include SurrealDB; resolvedFromMessageId points to message with SurrealDB option.",
    "- Input: My project needs work. => entities: none; tools: none.",
    "- Input: The feature is broken. => entities: none; tools: none.",
    "- Input: I'm building Schack Systems and shipping the first release in April. => project: Schack Systems; decision: shipping the first release in April.",
    "- Input: We need payment processing and user onboarding. Workspace: FinVault, no existing projects. => project: payment processing; project: user onboarding (top-level workstreams in the workspace).",
    "- Input: We need OAuth and SSO support. Workspace: FinVault, existing project: User Management. => feature: OAuth support; feature: SSO support (capabilities within an existing project).",
    "- Input: The platform will ingest chat, extract decisions and tasks, store them in SurrealDB, and render component cards for high-confidence entities. => task: extract decisions and tasks; decision: store them in SurrealDB; avoid extra entities for ingest/render clause fragments.",
    "- Input: Deduplicate features by embedding similarity and keep the more descriptive name when merged. => feature: Deduplicate features by embedding similarity (single entity).",
    "",
    "Relationships:",
    "- Include only relationships that are explicitly grounded in the Current source text.",
    "- Each relationship must include kind, fromTempId, toTempId, confidence, fromText, toText.",
    "- Use uppercase snake case relationship kinds when possible (for example DEPENDS_ON, BLOCKS, RELATES_TO).",
    input.onboarding
      ? "Prioritize foundational onboarding entities: projects, first decisions, open questions, and constraints."
      : "Prioritize actionable entities and direct relationships.",
  ].join("\n");
}
